


all: Extended_Euclidean_Algo
	.\Extended_Euclidean_Algo

Extended_Euclidean_Algo: Extended_Euclidean_Algo.cpp
	g++ Extended_Euclidean_Algo.cpp -o Extended_Euclidean_Algo

clean:
	rm .\Extended_Euclidean_Algo